#!/bin/sh
# vim:sw=4:ts=4:et

set -e

case "$1" in
  "list"|"ls"|"synthesize"|"synth"|"bootstrap"|"deploy"|"watch"|"destroy"|"diff"|"metadata"|"context"|"docs"|"doc"|"doctor")
    set -- cdk "$@"
    ;;
  *)
    if [ "${1#-}" != "$1" ]; then
      set -- cdk "$@"
    fi
    ;;
esac

exec "$@"
