name: Build containers

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'refs/pull/*'
    tags:

jobs:
  matrix:
    name: Generate job matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Gather versions
        id: matrix
        uses: ./ci-matrix-action

  build:
    name: Build
    needs: [matrix]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.version }}
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          build-args: |
            AWS_CDK_VERSION=${{ matrix.version }}
          push: true
          tags: ${{ matrix.tags }}
